version: "3.3"

services:
  client:
    stdin_open: true
    container_name: dndclient
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 127.0.0.1:3001:3000